*ActorControlTarget, +PlaceFieldMarker, +PlaceFieldMarkerPreset, -Add…
karashiiro/FFXIVOpcodeWizard pull request #42
Opened 2020-11-26 11:07 UTC by Ra-Workspace

…StatusEffect

2020-11-26 16:13 UTC, karashiiro requested changes

2020-11-26 16:13 UTC, karashiiro commented on PacketDetection/ScannerRegistry.cs
> +            RegisterScanner("PrepareZoning", "Please find an Aetheryte and teleport to Lancers' Guild.",
Is there a reason why this location had to be changed? PrepareZoning is sent before ActorSetPos, so if the two scanners involve the same aetheryte location they can be resolved in one action.

2020-11-26 16:13 UTC, karashiiro commented on PacketDetection/ScannerRegistry.cs
> -            RegisterScanner("AddStatusEffect", "Please use Dia.",
Why does this need to be removed? If it's because it's job-specific you can just click the skip button on the UI.

2020-11-27 23:30 UTC, Ra-Workspace reviewed
ahhhhhhhhhhh, I didn't know pending status.. I am so stupid.

2020-11-27 23:30 UTC, Ra-Workspace commented on PacketDetection/ScannerRegistry.cs
> +            RegisterScanner("ActorControlTarget", "Please mark 1 to self.",
I know it happens when you set the target mark.

2020-11-27 23:30 UTC, Ra-Workspace commented on PacketDetection/ScannerRegistry.cs
> -            RegisterScanner("AddStatusEffect", "Please use Dia.",
this is same EffectResult and result also same.

https://github.com/SapphireServer/Sapphire/commit/1f4b2dafbb43600c414ac913b0b0e30854326489

2020-11-27 23:30 UTC, Ra-Workspace commented on PacketDetection/ScannerRegistry.cs
> +            RegisterScanner("ActorSetPos", "Please teleport to Mih Khetto's Amphitheatre via the Aetheryte.",
#38 

if you are in same field, you can receive this packet.

2020-11-27 23:30 UTC, Ra-Workspace commented on PacketDetection/ScannerRegistry.cs
> +                    BitConverter.ToUInt32(packet.Data, Offsets.IpcData + 0x08) == 7237);
I think it's the coordinates.

```
BitConverter.ToUInt32(packet.Data, Offsets.IpcData + 0x04) // x?
BitConverter.ToUInt32(packet.Data, Offsets.IpcData + 0x08) // y?
BitConverter.ToUInt32(packet.Data, Offsets.IpcData + 0x0C) // z?
```
 I don't know how to do and calculate..

2020-11-27 23:30 UTC, Ra-Workspace commented on PacketDetection/ScannerRegistry.cs
> +            RegisterScanner("PrepareZoning", "Please find an Aetheryte and teleport to Lancers' Guild.",
I don't know if it's a version difference or my problem, but I didn't get an ActorSetPos packet. So, I thought that first move Old Gridania anywhere and teleport to Mih Khetto's Amphitheatre. 

If there's no problem, I'll put it back.

2020-11-27 23:30 UTC, Ra-Workspace commented on PacketDetection/ScannerRegistry.cs
> -            RegisterScanner("AddStatusEffect", "Please use Dia.",
uh,, how to add line link(?) ? 😥

https://github.com/karashiiro/FFXIVOpcodeWizard/blob/master/PacketDetection/ScannerRegistry.cs#L245
I removed it because it was getting the same value earlier.

2020-11-27 23:30 UTC, Ra-Workspace commented on PacketDetection/ScannerRegistry.cs
> -            RegisterScanner("AddStatusEffect", "Please use Dia.",
It's good to think it's another way to get it. I'll put it back.

2020-11-28 18:15 UTC, karashiiro commented on PacketDetection/ScannerRegistry.cs
> +                    BitConverter.ToUInt32(packet.Data, Offsets.IpcData + 0x08) == 7237);
Pretty sure they're floats, but I'd have to check. If it works without the coordinates then that's great too.

2020-11-28 18:16 UTC, karashiiro commented on PacketDetection/ScannerRegistry.cs
> +            RegisterScanner("PrepareZoning", "Please find an Aetheryte and teleport to Lancers' Guild.",
This is fine actually, it should work the same way regardless of what the directions are. No worries here.

2020-11-28 18:18 UTC, karashiiro commented on PacketDetection/ScannerRegistry.cs
> -            RegisterScanner("AddStatusEffect", "Please use Dia.",
If it's the same scanner then it should be corrected, not changed to what it's currently scanning for. At any rate, if this scanner is returning the value for EffectResult then that's a bug; I'll fix that later. Outside the scope of this PR.

2020-11-28 18:19 UTC, karashiiro approved these changes

2020-11-28 18:19 UTC, merged